---
local:
  prompt: "[user@laptop ~]$"
  bash_shebang: "#!/bin/bash"

snippets: EPCC_ARCHER2_slurm
baseurl: "https://epcced.github.io/2025-10-14-archer2-intro-hpc"

remote:
  name: "ARCHER2"
  host_id: "EPCC_ARCHER2"
  login: "login.archer2.ac.uk"
  host: "ln03"
  node: "nid001053"
  location: "EPCC, The University of Edinburgh"
  homedir: "/home/ta215/ta215/userid"
  workdir: "/work/ta215/ta215/userid"
  user: "userid"
  prompt: "userid@ln03:~>"
  prompt_work: "userid@ln03:/work/ta215/ta215/userid>"
  module_python3: "cray-python"
  bash_shebang: "#!/bin/bash"

sched:
  name: "Slurm"
  partition: "standard"
  #reservation: "shortqos"
  qos: "short"
  budget: "short"
  submit:
    name: "sbatch"
    options: "--partition=standard --qos=short"
  queue:
    debug: ""
    testing: ""
  status: "squeue"
  flag:
    user: "-u userid"
    interactive: ""
    histdetail: "-l -j"
    name: "--job-name"
    time: "--time"
    queue: "--partition"
    nodes: "--nodes"
    tasks: ""
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct"
  project: "ta215"
